# Dockerfile for local development
# Files get mounted, not copied.

FROM 970605007005.dkr.ecr.eu-west-1.amazonaws.com/drupal/base
COPY config/extra.settings.php sites/default/extra.settings.php

# Override the entrypoint
COPY config/entrypoint-test.sh /entrypoint-test.sh
ENTRYPOINT ["/entrypoint-test.sh"]

CMD ["run-tests"]
